
Connected to pydev debugger (build 202.8194.22)
Oops! <class 'django.db.utils.IntegrityError'> occurred
{'_state': <django.db.models.base.ModelState object at 0x000002A3EFEA1430>, 'id': UUID('238712a3-fb5b-4010-a1a4-de9e4f6dfa57'), 'type': 'RO', 'slug': 'boston-ma-ro', 'display_name': 'Boston MA RO', 'site_code': 'X23', 'ssa_office_name': None, 'region': '1', 'ssa_last_updated': '2020-10-01', 'address1': "Thomas P. O'Neill, Jr. Federal Building", 'address2': '10 Causeway Street, Suite 565', 'city': 'Boston', 'state': 'MA', 'zipcode': '02222', 'tel_public': PhoneNumber(country_code=1, national_number=8888707578, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'tel_call_back': None, 'tel_admin': None, 'fax': PhoneNumber(country_code=1, national_number=8336130456, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'efile_fax': '', 'servicing_states': None, 'servicing_fos': None, 'servicing_zipcodes': None, 'latitude': '42.36189', 'longitude': '-71.062235', 'notes': None, 'modified': datetime.datetime(2020, 12, 12, 16, 26, 51, 166396, tzinfo=<UTC>)}

Oops! <class 'django.db.utils.IntegrityError'> occurred
{'_state': <django.db.models.base.ModelState object at 0x000002A3EFEFCBE0>, 'id': UUID('b0c5a20d-2b71-4c95-b3a2-a1b0e1ab60b2'), 'type': 'HO', 'slug': 'boston-ma-ho', 'display_name': 'Boston MA HO', 'site_code': 'T24', 'ssa_office_name': None, 'region': '1', 'ssa_last_updated': '2020-10-01', 'address1': '4Th Floor', 'address2': 'One Bowdoin Square', 'city': 'Boston', 'state': 'MA', 'zipcode': '02114', 'tel_public': PhoneNumber(country_code=1, national_number=8888707573, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'tel_call_back': None, 'tel_admin': None, 'fax': PhoneNumber(country_code=1, national_number=8337100405, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'efile_fax': PhoneNumber(country_code=1, national_number=8777875236, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'servicing_states': None, 'servicing_fos': None, 'servicing_zipcodes': None, 'latitude': '42.36189', 'longitude': '-71.062235', 'notes': None, 'modified': datetime.datetime(2020, 12, 12, 16, 26, 51, 176391, tzinfo=<UTC>)}

Oops! <class 'django.db.utils.IntegrityError'> occurred
{'_state': <django.db.models.base.ModelState object at 0x000002A3EFEFCEB0>, 'id': UUID('01d281af-572e-40b4-af38-897b16206d80'), 'type': 'HO', 'slug': 'new-york-ny-ho', 'display_name': 'New york NY HO', 'site_code': 'X69', 'ssa_office_name': None, 'region': '2', 'ssa_last_updated': '2020-10-01', 'address1': '3Rd Floor, Room 315', 'address2': '201 Varick Street', 'city': 'New York', 'state': 'NY', 'zipcode': '10014-9998', 'tel_public': PhoneNumber(country_code=1, national_number=8669649971, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'tel_call_back': None, 'tel_admin': None, 'fax': PhoneNumber(country_code=1, national_number=8333590113, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'efile_fax': PhoneNumber(country_code=1, national_number=8773798558, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'servicing_states': None, 'servicing_fos': None, 'servicing_zipcodes': None, 'latitude': '40.72834', 'longitude': '-74.006221', 'notes': None, 'modified': datetime.datetime(2020, 12, 12, 16, 26, 51, 509848, tzinfo=<UTC>)}

Oops! <class 'django.db.utils.IntegrityError'> occurred
{'_state': <django.db.models.base.ModelState object at 0x000002A3EFF1B8B0>, 'id': UUID('88ac96f2-4cdf-4eb0-bb32-d39f5efacdf2'), 'type': 'HO', 'slug': 'baltimore-md-ho', 'display_name': 'Baltimore MD HO', 'site_code': 'T21', 'ssa_office_name': None, 'region': '3', 'ssa_last_updated': '2020-10-01', 'address1': 'The Symphony Center, Room 300', 'address2': '1010 Park Avenue', 'city': 'Baltimore', 'state': 'MD', 'zipcode': '21201-5600', 'tel_public': PhoneNumber(country_code=1, national_number=8666133960, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'tel_call_back': None, 'tel_admin': None, 'fax': PhoneNumber(country_code=1, national_number=8337100399, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'efile_fax': PhoneNumber(country_code=1, national_number=8775488804, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'servicing_states': None, 'servicing_fos': None, 'servicing_zipcodes': None, 'latitude': '39.303029', 'longitude': '-76.618979', 'notes': None, 'modified': datetime.datetime(2020, 12, 12, 16, 26, 51, 637375, tzinfo=<UTC>)}

Oops! <class 'django.db.utils.IntegrityError'> occurred
{'_state': <django.db.models.base.ModelState object at 0x000002A3EFF1B970>, 'id': UUID('c83f863d-7686-41fe-85c6-deb673818559'), 'type': 'HO', 'slug': 'philadelphia-pa-ho', 'display_name': 'Philadelphia PA HO', 'site_code': 'R56', 'ssa_office_name': None, 'region': '3', 'ssa_last_updated': '2020-10-01', 'address1': 'Suite 502', 'address2': '833 Chestnut Street', 'city': 'Philadelphia', 'state': 'PA', 'zipcode': '19107', 'tel_public': PhoneNumber(country_code=1, national_number=8665729721, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'tel_call_back': None, 'tel_admin': None, 'fax': PhoneNumber(country_code=1, national_number=8333200687, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'efile_fax': PhoneNumber(country_code=1, national_number=8775488811, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'servicing_states': None, 'servicing_fos': None, 'servicing_zipcodes': None, 'latitude': '39.949764', 'longitude': '-75.155156', 'notes': None, 'modified': datetime.datetime(2020, 12, 12, 16, 26, 51, 906351, tzinfo=<UTC>)}

Oops! <class 'django.db.utils.IntegrityError'> occurred
{'_state': <django.db.models.base.ModelState object at 0x000002A3EFF2F4F0>, 'id': UUID('6da3e40d-6f41-463a-be8d-ae85588c5db9'), 'type': 'NCAC', 'slug': 'louisville-ky-ncac', 'display_name': 'Louisville KY NCAC', 'site_code': '', 'ssa_office_name': None, 'region': '4', 'ssa_last_updated': '2020-10-01', 'address1': 'Gene Snyder U.S. Courthouse', 'address2': '601 West Broadway, Lower Level', 'city': 'Louisville', 'state': 'KY', 'zipcode': '40202', 'tel_public': PhoneNumber(country_code=1, national_number=8663671224, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'tel_call_back': None, 'tel_admin': None, 'fax': PhoneNumber(country_code=1, national_number=8334140619, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'efile_fax': '', 'servicing_states': None, 'servicing_fos': None, 'servicing_zipcodes': None, 'latitude': '38.246983', 'longitude': '-85.762468', 'notes': None, 'modified': datetime.datetime(2020, 12, 12, 16, 26, 52, 380946, tzinfo=<UTC>)}

Oops! <class 'django.db.utils.IntegrityError'> occurred
{'_state': <django.db.models.base.ModelState object at 0x000002A3EFF2FEE0>, 'id': UUID('efa02056-d046-4ed4-a479-1500de1a6b1f'), 'type': 'HO', 'slug': 'dallas-tx-ho', 'display_name': 'Dallas TX HO', 'site_code': 'T18', 'ssa_office_name': None, 'region': '6', 'ssa_last_updated': '2020-10-01', 'address1': 'Building 9, Suite 500', 'address2': '12790 Merit Drive', 'city': 'Dallas', 'state': 'TX', 'zipcode': '75251', 'tel_public': PhoneNumber(country_code=1, national_number=8663317135, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'tel_call_back': None, 'tel_admin': None, 'fax': PhoneNumber(country_code=1, national_number=8336311014, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'efile_fax': PhoneNumber(country_code=1, national_number=8779045524, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'servicing_states': None, 'servicing_fos': None, 'servicing_zipcodes': None, 'latitude': '32.922686', 'longitude': '-96.770963', 'notes': None, 'modified': datetime.datetime(2020, 12, 12, 16, 26, 53, 164289, tzinfo=<UTC>)}

Oops! <class 'django.db.utils.IntegrityError'> occurred
{'_state': <django.db.models.base.ModelState object at 0x000002A3EFF1B1C0>, 'id': UUID('49db705e-e799-4b9f-beb9-a4269091bfd3'), 'type': 'HO', 'slug': 'houston-tx-ho', 'display_name': 'Houston TX HO', 'site_code': 'Y34', 'ssa_office_name': None, 'region': '6', 'ssa_last_updated': '2020-10-01', 'address1': '9700 Richmond Avenue', 'address2': 'Suite 200', 'city': 'Houston', 'state': 'TX', 'zipcode': '77042', 'tel_public': PhoneNumber(country_code=1, national_number=8667795456, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'tel_call_back': None, 'tel_admin': None, 'fax': PhoneNumber(country_code=1, national_number=8336480167, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'efile_fax': PhoneNumber(country_code=1, national_number=8778471603, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'servicing_states': None, 'servicing_fos': None, 'servicing_zipcodes': None, 'latitude': '29.74187', 'longitude': '-95.55822', 'notes': None, 'modified': datetime.datetime(2020, 12, 12, 16, 26, 53, 215275, tzinfo=<UTC>)}

Oops! <class 'django.db.utils.IntegrityError'> occurred
{'_state': <django.db.models.base.ModelState object at 0x000002A3EFF3C730>, 'id': UUID('958235b8-1316-45a0-aace-7ddcae893664'), 'type': 'HO', 'slug': 'los-angeles-ca-ho', 'display_name': 'Los angeles CA HO', 'site_code': 'T30', 'ssa_office_name': None, 'region': '9', 'ssa_last_updated': '2020-10-01', 'address1': 'Suite 400', 'address2': '12121 Wilshire Boulevard', 'city': 'Los Angeles', 'state': 'CA', 'zipcode': '90025', 'tel_public': PhoneNumber(country_code=1, national_number=8667482089, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'tel_call_back': None, 'tel_admin': None, 'fax': PhoneNumber(country_code=1, national_number=8334140623, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'efile_fax': PhoneNumber(country_code=1, national_number=8773944585, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'servicing_states': None, 'servicing_fos': None, 'servicing_zipcodes': None, 'latitude': '34.0680038', 'longitude': '-118.4253509', 'notes': None, 'modified': datetime.datetime(2020, 12, 12, 16, 26, 53, 703246, tzinfo=<UTC>)}

Oops! <class 'django.db.utils.IntegrityError'> occurred
{'_state': <django.db.models.base.ModelState object at 0x000002A3EFF3CC10>, 'id': UUID('4b87570d-4122-490f-b2ed-9ba047360112'), 'type': 'HO', 'slug': 'phoenix-az-ho', 'display_name': 'Phoenix AZ HO', 'site_code': 'T1R', 'ssa_office_name': None, 'region': '9', 'ssa_last_updated': '2020-10-01', 'address1': 'Suite 430', 'address2': '18444 North 25Th Avenue', 'city': 'Phoenix', 'state': 'AZ', 'zipcode': '85023', 'tel_public': PhoneNumber(country_code=1, national_number=8777843690, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'tel_call_back': None, 'tel_admin': None, 'fax': PhoneNumber(country_code=1, national_number=8336760149, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'efile_fax': PhoneNumber(country_code=1, national_number=8778471601, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'servicing_states': None, 'servicing_fos': None, 'servicing_zipcodes': None, 'latitude': '33.653301', 'longitude': '-112.113038', 'notes': None, 'modified': datetime.datetime(2020, 12, 12, 16, 26, 53, 807369, tzinfo=<UTC>)}

Oops! <class 'django.db.utils.IntegrityError'> occurred
{'_state': <django.db.models.base.ModelState object at 0x000002A3EFEFCD00>, 'id': UUID('43f71f62-1e6a-4189-86ba-162ead3db4e4'), 'type': 'NCAC', 'slug': 'richmond-ca-ncac', 'display_name': 'Richmond CA NCAC', 'site_code': '', 'ssa_office_name': None, 'region': '9', 'ssa_last_updated': '2020-10-01', 'address1': 'Frank Hagel Federal Building', 'address2': '1221 Nevin Avenue, 6Th Floor', 'city': 'Richmond', 'state': 'CA', 'zipcode': '94801', 'tel_public': PhoneNumber(country_code=1, national_number=8552958304, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'tel_call_back': None, 'tel_admin': None, 'fax': PhoneNumber(country_code=1, national_number=8334140621, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None), 'efile_fax': '', 'servicing_states': None, 'servicing_fos': None, 'servicing_zipcodes': None, 'latitude': '37.937585', 'longitude': '-122.357152', 'notes': None, 'modified': datetime.datetime(2020, 12, 12, 16, 26, 53, 826812, tzinfo=<UTC>)}


Process finished with exit code 0
